print('  へ　　　　　／|')
print(' /＼7　　　 ∠＿/')
print('/　│　　  ／　／')
print('│　Z ＿,＜　／　　 /`ヽ')
print('│　　　　　ヽ　　 /　　>')
print('　Y　　　　　`　 /　　/')
print('ｲ●　､　●　　⊂⊃〈　　/')
print('()　 へ　　　　|　＼〈')
print('　>ｰ ､_　 ィ　 │ ／／')
print('　/ へ　　 /　ﾉ＜| ＼＼')
print('　ヽ_ﾉ　　(_／　 │／／')
print('　7　　　　　　　|／')
print('                 ')
print('　＞―r￣￣`ｰ―＿')
